[package]
name = "millegrilles_common_rust"
version = "2022.5.0"
edition = "2021"

[dependencies]

async-std = "1.9.0"
async-tar = { version = "0.4.2" }
bytes = { version = "1.1.0" }
log = { version = "0.4.14", features = ["max_level_trace", "release_max_level_info"] }
env_logger = { version = "0.9.0" }
num-traits = "0.2.14"
rand = "0.7"
reqwest = { version = "0.11.6", features = ["default-tls", "rustls-tls", "rustls-tls-manual-roots", "json", "multipart", "stream"] }
tempfile = { version = "3.2.0" }
xz2 = { version = "0.1.7", features = ["tokio"] }

# Tokio, async
async-recursion = "*"
async-trait = "0.1.51"
tokio = { version = "1.11.0", features = ["full"] }
tokio-stream = { version = "0.1.7" }
# tokio-tar = { version = "0.3.0" }
tokio-util = { version = "*", features = ["codec", "io"] }

# Crypto et certs
openssl = { version = "0.10.29", features = ["vendored"] }
x509-parser = { "version" = "0.10.0" }
multibase = "0.9.1"
multicodec = "0.1.0"
multihash = "0.14.0"
blake2 = "0.10.2"
# chacha20poly1305 = { version= "0.9.0", features = ["stream"] }
aead = { version = "0.4", default-features = false, features = ['alloc'] }
chacha20 = { version = "0.8", features = ["zeroize"] }
cipher = "0.3"
dryoc = { version = "^0.3.11" }
poly1305 = "0.7"
zeroize = { version = ">=1, <1.5", default-features = false }

# JSON
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Formats
chrono = { version = "0.4.19", features = ["serde"] }
url = { version = "2.2.2", features = ["serde"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
substring = { version = "1.4.5" }

# MongoDB
mongodb = { version = "2.1.0", default-features = false, features = ["tokio-runtime", "bson-chrono-0_4"] }
# bson = "2.0.0"

# RabbitMQ
lapin = { "version" = "1.8.0" }
futures = "0.3.1"
futures-util = "0.3.16"
tokio-amqp = { version = "1.0.0" }

redis = { version = "0.21.5", features = ["tokio-comp", "tokio-native-tls-comp"] }

#[dev-dependencies]
#aead = { version = "0.4", features = ["dev"], default-features = false }
