[package]
name = "millegrilles_common_rust"
version = "1.45.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

log = { version = "0.4.14", features = ["max_level_debug", "release_max_level_info"] }
num-traits = "0.2.14"
rand = "0.7"
tar = { version = "0.4.37" }
tempfile = { version = "3.2.0" }
xz2 = { version = "0.1.6", features = ["tokio"] }

# Tokio, async
async-trait = "0.1.51"
tokio = { version = "1.9.0", features = ["full"] }
tokio-stream = { version = "0.1.7" }

# Crypto et certs
openssl = { version = "0.10.29", features = ["vendored"] }
x509-parser = { "version" = "0.10.0" }
multibase = "0.9.1"
multicodec = "0.1.0"
multihash = "0.14.0"

# JSON
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Formats
chrono = { version = "0.4.19" }
uuid = { version = "0.8.2", features = ["serde", "v4"] }

# MongoDB
mongodb = { version = "1.2.2", default-features = false, features = ["async-std-runtime"] }
bson = "1.2.3"

# RabbitMQ
lapin = { "version" = "1.7.1" }
futures = "0.3.1"
futures-util = "0.3.16"
tokio-amqp = { version = "1.0.0" }
